// Generated by Wrangler on Thu May 16 2024 10:37:04 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	BROWSER: DurableObjectNamespace;
	BUCKET: R2Bucket;
	MYBROWSER: Fetcher;
}
